// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDhBgPj829xYAf-G_YVQNM1bQt7Lld2i2M',
    appId: '1:129827125705:web:d03d5399160ce6bb291018',
    messagingSenderId: '129827125705',
    projectId: 'fashion-shops-36134',
    authDomain: 'fashion-shops-36134.firebaseapp.com',
    databaseURL: 'https://fashion-shops-36134-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'fashion-shops-36134.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAEE3RiPxv5PspCcy56_NF7zEzi5Dv10E0',
    appId: '1:129827125705:android:497e575f1e8f1212291018',
    messagingSenderId: '129827125705',
    projectId: 'fashion-shops-36134',
    databaseURL: 'https://fashion-shops-36134-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'fashion-shops-36134.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAWXfQb77knSeJB0MFyao6YxDOfEmwNaPY',
    appId: '1:129827125705:ios:dd4ac2e5d16f1750291018',
    messagingSenderId: '129827125705',
    projectId: 'fashion-shops-36134',
    databaseURL: 'https://fashion-shops-36134-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'fashion-shops-36134.appspot.com',
    androidClientId: '129827125705-dg0fqnn4bp03ht9lk01fjacpekia412q.apps.googleusercontent.com',
    iosClientId: '129827125705-un3v2ubvc886687mnelu7b361sr6po4b.apps.googleusercontent.com',
    iosBundleId: 'com.example.fashionShops',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAWXfQb77knSeJB0MFyao6YxDOfEmwNaPY',
    appId: '1:129827125705:ios:545385939ca9c730291018',
    messagingSenderId: '129827125705',
    projectId: 'fashion-shops-36134',
    databaseURL: 'https://fashion-shops-36134-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'fashion-shops-36134.appspot.com',
    androidClientId: '129827125705-dg0fqnn4bp03ht9lk01fjacpekia412q.apps.googleusercontent.com',
    iosClientId: '129827125705-5nsc71ouv5g1eei7rlijrs5tq14rhl4o.apps.googleusercontent.com',
    iosBundleId: 'com.example.fashionShops.RunnerTests',
  );
}
